Update dotnet-desktop.yml

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -25,24 +25,11 @@ jobs:
           dotnet-version: ${{ matrix.dotnet }}
       - name: Build
         run: dotnet build --configuration Release
-#       - name: Unit test
-#         run: dotnet test --configuration Release --no-build --no-restore --verbosity normal
-      - name: Cache artifacts
-        id: cache-ddl
-        uses: actions/cache@v3
-        with:
-          key: artifacts
-          path: Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll
-          
-      - name: Cache artifacts
-        id: cache-ddl-2
-        uses: actions/cache@v3
-        with:
-          key: artifacts
-          path: Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll
+      - name: Unit test
+        run: dotnet test --configuration Release --no-build --no-restore --verbosity normal
          
-  sign:
-    name: Sign
+  release:
+    name: Release
     if: startsWith(github.ref, 'refs/tags/')
     needs: [test]
     runs-on: ${{ matrix.os }}
@@ -71,60 +58,37 @@ jobs:
         uses: actions/checkout@v2
         with:
           submodules: recursive
-          
 
       - name: Sign
         shell: bash
         run: |
           dotnet build --configuration Release
-#           # Push unsigned DLL to S3
-#           version_id=$( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll  --acl bucket-owner-full-control | jq '.VersionId' )
-#           job_id=""
-#           # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
-#           # Will sleep for 5 seconds between retries.
-#           for (( i=0; i<3; i++ ))
-#           do
-#             # Get job ID
-#             id=$( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id ${version_id} | jq -r '.TagSet[0].Value' )
-#             if [ $id != "null" ]
-#             then
-#               job_id=$id
-#               break
-#             fi
-#             sleep 5s
-#           done
-#           if [[ $job_id = "" ]]
-#           then
-#              echo "Exiting because unable to retrieve job ID"
-#              exit 1
-#           fi
-#           # Poll signed S3 bucket to see if the signed artifact is there
-#           aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id}
-#           # Get signed DLL from S3
-#           aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id} Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll  
+          # Push unsigned DLL to S3
+          version_id=$( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll  --acl bucket-owner-full-control | jq '.VersionId' )
+          job_id=""
+          # Attempt to get Job ID from bucket tagging, will retry up to 3 times before exiting with a failure code.
+          # Will sleep for 5 seconds between retries.
+          for (( i=0; i<3; i++ ))
+          do
+            # Get job ID
+            id=$( aws s3api get-object-tagging --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --version-id ${version_id} | jq -r '.TagSet[0].Value' )
+            if [ $id != "null" ]
+            then
+              job_id=$id
+              break
+            fi
+            sleep 5s
+          done
+          if [[ $job_id = "" ]]
+          then
+             echo "Exiting because unable to retrieve job ID"
+             exit 1
+          fi
+          # Poll signed S3 bucket to see if the signed artifact is there
+          aws s3api wait object-exists --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id}
+          # Get signed DLL from S3
+          aws s3api get-object --bucket ${{ secrets.AWS_SIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }}-${job_id} Amazon.IonHashDotnet/bin/Release/netstandard2.0/Amazon.IonHashDotnet.dll  
 
-  release:
-    name: release
-    if: startsWith(github.ref, 'refs/tags/')
-#     needs: [sign]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ windows-latest ]
-        dotnet: ['2.1']
-      
-    steps:
-    - name: Git Checkout
-      uses: actions/checkout@v2
-      with:
-        submodules: recursive
-
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: ${{ matrix.dotnet }}
-        
-    - name: release
-      run: |
-        dotnet build --configuration Release
-        dotnet pack --configuration Release --no-build
+      - name: release
+        run: |
+          dotnet pack --configuration Release --no-build
